### ISSUE TITLE
Calculating Water

### ISSUE THREAD

**Issue by SamiSha99** [FACN3/Water-you-talking-about#2]
# User Story:

As a water consumer, 
I want, to calculate my overall water consumption.
So that i can reduce my water expenses  

# Acceptance criteria 

- [x] [Gather data on  how much the water costs](https://github.com/FACN3/Water-you-talking-about/issues/11#issuecomment-362914332)
- [x] [Calculator for water consumptions.](https://github.com/FACN3/washinator/issues/7)
- [x] [A way to convert liters used to money](https://github.com/FACN3/washinator/issues/9) rel #11
